accounts/urls.py
from django.urls import path
from django.contrib.auth.views import LoginView, LogoutView

from accounts.views import signup

urlpatterns = [
    path("login/", LoginView.as_view(), name="login"),
    path("logout/", LogoutView.as_view(), name="logout"),
    path("signup/", signup, name="signup"),
]

projects/urls.py
from django.urls import path

from projects.views import (
    ProjectListView,
    ProjectDetailView,
    ProjectCreateView,
)

urlpatterns = [
    path("", ProjectListView.as_view(), name="list_projects"),
    path("<int:pk>/", ProjectDetailView.as_view(), name="show_project"),
    path("create/", ProjectCreateView.as_view(), name="create_project"),
]

tasks/urls.py
from django.urls import path

from tasks.views import (
    CreateTaskView,
    TaskListView,
    UpdateTaskView,
)


urlpatterns = [
    path("create/", CreateTaskView.as_view(), name="create_task"),
    path("mine/", TaskListView.as_view(), name="show_my_tasks"),
    path("<int:pk>/complete/", UpdateTaskView.as_view(), name="complete_task"),
]

tracker/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic.base import RedirectView

urlpatterns = [
    path("admin/", admin.site.urls),
    path("projects/", include("projects.urls")),
    path("", RedirectView.as_view(url="/projects/"), name="home"),
    path("accounts/", include("accounts.urls")),
    path("tasks/", include("tasks.urls")),
]

accounts/models.py
# Create your models here.

projects/models.py
from django.db import models
from django.conf import settings

USER_MODEL = settings.AUTH_USER_MODEL


class Project(models.Model):
    name = models.CharField(max_length=200)
    description = models.TextField()
    members = models.ManyToManyField(USER_MODEL,
                                     related_name="projects")

    def __str__(self):
        return self.name

tasks/models.py
from django.db import models
from django.conf import settings
from projects.models import Project

USER_MODEL = settings.AUTH_USER_MODEL


class Task(models.Model):
    name = models.CharField(max_length=200)
    start_date = models.DateTimeField()
    due_date = models.DateTimeField()
    is_completed = models.BooleanField(default=False)
    project = models.ForeignKey(
        Project, on_delete=models.CASCADE, related_name="tasks"
    )
    assignee = models.ForeignKey(
        USER_MODEL, null=True, related_name="tasks", on_delete=models.SET_NULL
    )

    def __str__(self):
        return self.name

accounts/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django.contrib.auth import login

# Create your views here.


def signup(request):
    if request.method == "POST":
        form = UserCreationForm(request.POST)
        if form.is_valid():
            username = request.POST.get("username")
            password = request.POST.get("password1")
            user = User.objects.create_user(
                username=username,
                password=password,
            )
            user.save()
            login(request, user)
            return redirect("home")
    else:
        form = UserCreationForm()
    context = {
        "form": form,
    }
    return render(request, "registration/signup.html", context)

projects/views.py
from django.shortcuts import redirect
from django.views.generic.detail import DetailView
from django.views.generic.edit import CreateView
from django.views.generic.list import ListView
from django.contrib.auth.mixins import LoginRequiredMixin
from projects.models import Project

# Create your views here.


class ProjectListView(LoginRequiredMixin, ListView):
    model = Project
    template_name = "projects/list.html"

    def get_queryset(self):
        return Project.objects.filter(members=self.request.user)


class ProjectDetailView(LoginRequiredMixin, DetailView):
    model = Project
    template_name = "projects/detail.html"


class ProjectCreateView(LoginRequiredMixin, CreateView):
    model = Project
    template_name = "projects/create.html"
    fields = ["name", "description", "members"]

    def form_valid(self, form):
        item = form.save(commit=False)
        item.save()
        form.save_m2m()

        return redirect("list_projects")

tasks/views.py
from django.urls import reverse_lazy
from django.views.generic.edit import CreateView, UpdateView
from django.views.generic.list import ListView
from django.contrib.auth.mixins import LoginRequiredMixin
from tasks.models import Task

# Create your views here.


class CreateTaskView(LoginRequiredMixin, CreateView):
    model = Task
    template_name = "tasks/create.html"
    fields = ["name", "start_date", "due_date", "project", "assignee"]

    def get_success_url(self):
        return reverse_lazy("show_project", args=[self.object.id])


class TaskListView(LoginRequiredMixin, ListView):
    model = Task
    template_name = "tasks/list.html"

    def get_queryset(self):
        return Task.objects.filter(assignee=self.request.user)


class UpdateTaskView(LoginRequiredMixin, UpdateView):
    model = Task
    fields = ["is_completed"]

    def get_success_url(self):
        return reverse_lazy("show_my_tasks")

projects/templates/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    {% load static %}
    <link rel="stylesheet" href="{%static 'app.css'%}" />
    <title>Taskmanager+</title>
  </head>
  <body class="home_background">
    <header>
      <h1 class="home_title">
        Taskmanager+
      </h1>
      <p class="home_quote">For all your task managing needs!
      </p>
      <nav>
        <ul class="navigation">
          {% if user.is_authenticated %}
          <dl class="sign_up">
            <a class="base_links" href="{% url 'show_my_tasks' %}">My tasks</a>
          </dl>
          <dl class="sign_up">
            <a class="base_links" href="{% url 'list_projects' %}">My projects</a>
          </dl>
          <dl class="sign_up">
            <a class="base_links" href="{% url 'logout' %}">Logout</a>
          </dl>
          {% if user.is_staff %}
          <dl>
            <a class="admin_button" href="{% url 'admin:index' %}">Admin</a></dl>
          {% endif %} 
          {% else %}
          <dl class="sign_up">
            <a class="base_links" href="{% url 'login' %}">Login</a></dl>
          <dl class="sign_up">
            <a class="base_links" href="{% url 'signup' %}">Signup</a>
          </dl>
          {% endif %}
        </ul>
      </nav>
    </header>
    <main>{% block content %} {% endblock content %}</main>
  </body>
</html>

projects/templates/projects/create.html
{% extends 'base.html' %}

{% block content %}
    <div class="login_form">
        <h1 class="project_detail" >Create a new project</h1>
        <form method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <button class="list_button">Create</button>
        </form>
    </div>
{% endblock content %}

projects/templates/projects/detail.html
{% extends 'base.html' %}
{% load markdownify %}

{% block content %}
    <div>
        <button class="list_button"><a class="tasks2" href="{% url 'create_task' %}">Create a new task</a></button>
        <h1 class="project_title">{{ project.name }}</h1>
        <p class="project_title">{{ project.description}}</p>
        {% if project.tasks.all|length %}
            <table class="project_table">
                <thead>
                    <tr>
                        <th class= "project_detail">Name</th>
                        <th class= "project_detail">Assignee</th>
                        <th class= "project_detail">Start date</th>
                        <th class= "project_detail">Due date</th>
                        <th class= "project_detail">Is completed</th>
                    </tr>
                </thead>
                <tbody>
                    {% for task in project.tasks.all %}
                        <tr>
                            <td class= "project_detail">{{ task.name }}</td>
                            <td class= "project_detail">{{ task.assignee }}</td>
                            <td class= "project_detail">{{ task.start_date|date:"m-d-Y" }}</td>
                            <td class= "project_detail">{{ task.due_date|date:"m-d-Y" }}</td>
                            <td class="project_detail">{{ task.is_completed }}</td>
                        </tr>
                    {% endfor %}
                </tbody>
            </table>
        {% else %}
            <p>This project has no tasks</p>
        {% endif %}
    </div>
{% endblock content %}

projects/templates/projects/list.html
{% extends 'base.html' %}

{% block content %}
    <div>
        <div>
        <button class="list_button"><a class="list_link" href="{% url 'create_project' %}">Create a new project</a></button>
        </div>
        {% if not project_list %}
            <p>You are not assigned to any projects</p>
        {% else %}
            <table class="project_table">
                <thead>
                    <tr>
                        <th>Name</th>
                        <th>Number of tasks</th>
                    </tr>
                </thead>
                <tbody>
                    {% for project in project_list %}
                        <tr>
                            <td>
                                <a class="tasks" href="{% url 'show_project' project.id %}">
                                    {{ project.name }}
                                </a>
                            </td>
                            <td>{{ project.tasks.all|length }}</td>
                        </tr>
                    {% endfor %}
                </tbody>
        {% endif %}
    </table>
    </div>
{% endblock content %}

projects/templates/tasks/create.html
{% extends 'base.html' %}

{% block content %}
    <div class="login_form">
        <h1 class="task_detail ">Create a new task</h1>
        <form method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <button class="list_button">Create</button>
        </form>
    </div>
{% endblock content %}

projects/templates/tasks/list.html
{% extends 'base.html' %}

{% block content %}
    <div>
        <h1 class="project_detail">My Tasks</h1>
        {% if not task_list %}
            <p>You have no tasks</p>
        {% else %}
            <table class="project_table">
                <thead>
                    <tr>
                        <th>Name</th>
                        <th>Start date</th>
                        <th>End date</th>
                        <th>Is completed</th>
                    </tr>
                </thead>
                <tbody>
                    {% for task in task_list %}
                        <tr>
                            <form method="post" action="{% url 'complete_task' task.id %}">
                                {% csrf_token %}
                                <input type="hidden" name="is_completed" value="True">
                            <td>{{ task.name }}</td>
                            <td>{{ task.start_date|date:"m-d-Y" }}</td>
                            <td>{{ task.due_date|date:"m-d-Y" }}</td>
                            <td>{{ task.is_completed  }}</td>
                            <td><button class="task_button">Complete</button>
                            </form>

                            </td>
                        </tr>
                    {% endfor %}
                </tbody>
        {% endif %}
    </table>
    </div>
{% endblock content %}